name: Deploy ToDo frontend on K3s

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Prepare Kaniko build context
        run: |
          mkdir -p /home/admin/build/todo-frontend
          cp Dockerfile /home/admin/build/todo-frontend/
          cp nginx.conf /home/admin/build/todo-frontend/
          cp -r dist /home/admin/build/todo-frontend/

      - name: Create Kaniko build job
        run: |
          sudo k3s kubectl apply -f k8s/kaniko-build-job.yaml

      - name: Wait for Kaniko build to finish
        run: |
          while [[ $(sudo k3s kubectl get job kaniko-build -o jsonpath='{.status.succeeded}') != "1" ]]; do
            echo "Waiting for kaniko-build to finish..."
            sleep 5
          done

      - name: Clean up Kaniko build job
        run: |
          sudo k3s kubectl delete job kaniko-build --ignore-not-found

      - name: Delete old deployment if exists
        run: |
          sudo k3s kubectl delete deployment todo-frontend --ignore-not-found
          sudo k3s kubectl delete service todo-frontend --ignore-not-found

      - name: Apply Kubernetes manifests
        run: |
          sudo k3s kubectl apply -f k8s/deployment.yaml
          sudo k3s kubectl apply -f k8s/service.yaml
